version: '3'

services:

  web:
    image: nginx:alpine
    container_name: web_tshirt
    restart: always
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"

  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    restart: always
    container_name: app_tshirt
    volumes:
      - ./:/var/www

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./app/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tshirt_basa
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    container_name: db_tshirt
  
  #phpmyadmin:
   # image: phpmyadmin
    #restart: always
    #ports:
     # - "8082:80"
    #environment:
     # MYSQL_ROOT_PASSWORD: root
     # PMAHOST: db
      #PMAUSER: root
      #PMA_PASSWORD: root
      #container_name: phpmyadmin
    


